export const images = {
  hero: require('../assets/hero-room.png'),
  homeAtelierHero: require('../assets/home-atelier-hero.png'),
  homeSliderAtelier: require('../assets/home-slider-atelier.jpg'),
  homeSliderNaturalLight: require('../assets/home-slider-natural-light.jpg'),
  homeSliderArchway: require('../assets/home-slider-archway.jpg'),
  shopHeroConfidence: require('../assets/shop-hero-confidence.png'),
  locked: require('../assets/search-locked-preview.jpg'),
  'arrival-1.jpg': require('../assets/arrival-1.jpg'),
  'arrival-2.jpg': require('../assets/arrival-2.jpg'),
  'arrival-3.jpg': require('../assets/arrival-3.jpg'),
  'arrival-4.jpg': require('../assets/arrival-4.jpg'),
  'arrival-5.jpg': require('../assets/arrival-5.jpg'),
  'arrival-6.jpg': require('../assets/arrival-6.jpg'),
  'category-1.jpg': require('../assets/category-1.jpg'),
  'category-tops-stack.png': require('../assets/category-tops-stack.png'),
  'category-tops-updated.jpg': require('../assets/category-tops-updated.jpg'),
  'category-2.jpg': require('../assets/category-2.jpg'),
  'category-tshirts-updated.jpg': require('../assets/category-tshirts-updated.jpg'),
  'category-3.jpg': require('../assets/category-3.jpg'),
  'category-4.jpg': require('../assets/category-4.jpg'),
  'category-bottoms-updated.jpg': require('../assets/category-bottoms-updated.jpg'),
  'category-5.jpg': require('../assets/category-5.jpg'),
  'category-6.jpg': require('../assets/category-6.jpg'),
  'category-shoes-updated.jpg': require('../assets/category-shoes-updated.jpg'),
  'category-7.jpg': require('../assets/category-7.jpg'),
  'category-8.jpg': require('../assets/category-8.jpg'),
  'category-eyewear-updated.jpg': require('../assets/category-eyewear-updated.jpg'),
  'category-generated/accessories.png': require('../assets/category-generated/accessories.png'),
  'category-generated/beauty.png': require('../assets/category-generated/beauty.png'),
  'category-generated/bottomwear.png': require('../assets/category-generated/bottomwear.png'),
  'category-generated/dresses.png': require('../assets/category-generated/dresses.png'),
  'category-generated/eyewear.png': require('../assets/category-generated/eyewear.png'),
  'category-generated/home-kitchen.png': require('../assets/category-generated/home-kitchen.png'),
  'category-generated/innerwear.png': require('../assets/category-generated/innerwear.png'),
  'category-generated/jackets.png': require('../assets/category-generated/jackets.png'),
  'category-generated/jeans.png': require('../assets/category-generated/jeans.png'),
  'category-generated/jewellery.png': require('../assets/category-generated/jewellery.png'),
  'category-generated/kids-fashion.png': require('../assets/category-generated/kids-fashion.png'),
  'category-generated/kurti-dress-material.png': require('../assets/category-generated/kurti-dress-material.png'),
  'category-generated/lounge.png': require('../assets/category-generated/lounge.png'),
  'category-generated/men-footwear.png': require('../assets/category-generated/men-footwear.png'),
  'category-generated/men-shirts.png': require('../assets/category-generated/men-shirts.png'),
  'category-generated/new-arrivals.png': require('../assets/category-generated/new-arrivals.png'),
  'category-generated/saree.png': require('../assets/category-generated/saree.png'),
  'category-generated/sleepwear.png': require('../assets/category-generated/sleepwear.png'),
  'category-generated/sneakers.png': require('../assets/category-generated/sneakers.png'),
  'category-generated/tops.png': require('../assets/category-generated/tops.png'),
  'category-generated/tshirts.png': require('../assets/category-generated/tshirts.png'),
  'category-generated/watches.png': require('../assets/category-generated/watches.png'),
  'category-generated/women-footwear.png': require('../assets/category-generated/women-footwear.png'),
  'search-shirt-1.jpg': require('../assets/search-shirt-1.jpg'),
  'search-shirt-2.jpg': require('../assets/search-shirt-2.jpg'),
  'search-shirt-3.jpg': require('../assets/search-shirt-3.jpg'),
  'search-shirt-4.jpg': require('../assets/search-shirt-4.jpg'),
  'trending-1.jpg': require('../assets/trending-1.jpg'),
  'trending-2.jpg': require('../assets/trending-2.jpg'),
  'trending-3.jpg': require('../assets/trending-3.jpg'),
  'trending-4.jpg': require('../assets/trending-4.jpg'),
  'trending-5.jpg': require('../assets/trending-5.jpg'),
  'trending-6.jpg': require('../assets/trending-6.jpg')
};

export const categories = [
  ['Tops', 'category-generated/tops.png', 'tops'],
  ['Bottoms', 'category-generated/bottomwear.png', 'bottoms'],
  ['Shirts', 'category-generated/men-shirts.png', 'shirts'],
  ['T-Shirts', 'category-generated/tshirts.png', 't-shirts'],
  ['Pants', 'category-generated/bottomwear.png', 'pants'],
  ['Jeans', 'category-generated/jeans.png', 'jeans'],
  ['Jackets', 'category-generated/jackets.png', 'jackets'],
  ['Shoes', 'category-generated/sneakers.png', 'shoes'],
  ['Watches', 'category-generated/watches.png', 'watches'],
  ['Accessories', 'category-generated/accessories.png', 'accessories'],
  ['Ethnic Wear', 'category-generated/kurti-dress-material.png', 'ethnic wear'],
  ['Eyewear', 'category-generated/eyewear.png', 'eyewear'],
  ['Innerwear', 'category-generated/innerwear.png', 'innerwear'],
  ['Sleepwear', 'category-generated/sleepwear.png', 'sleepwear']
];

export const infoPages = {
  women: ['For Women', 'Try new silhouettes with less guessing.', 'A dedicated shopping entry point for shirts, denim, jackets, accessories, and AI-powered outfit previews.', 'arrival-4.jpg'],
  sale: ['Sale', 'Better deals, fewer fit doubts.', 'Browse discounted products and use try-on previews before finalizing your picks.', 'search-shirt-2.jpg'],
  gift: ['Gift Cards', 'Style confidence makes a good gift.', 'Gift cards can be used toward shopping and try-on tokens when payments are connected.', 'hero'],
  about: ['About', 'Shopping online should feel more certain.', 'Lookmefy combines product discovery with AI try-on previews so shoppers can compare styles with confidence.', 'hero'],
  support: ['Help', 'Support for shopping and try-on.', 'Find answers about shipping, returns, profile photos, tokens, and account access.', 'search-shirt-4.jpg'],
  contact: ['Contact', 'Tell us what you need.', 'For order, token, account, and AI try-on questions, reach the Lookmefy support team.', 'hero'],
  privacy: ['Privacy', 'Your try-on profile is personal.', 'Account details, full-body photos, token usage, and shopping activity should be handled carefully.', 'hero'],
  terms: ['Terms', 'Terms and conditions.', 'This page outlines where account, token, shopping, and AI try-on usage rules live.', 'hero']
};
